# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ntest2',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/ntest2',
                'lib_path': 'ntest2'},
  'syms': {'ntest2.core': {'ntest2.core.foo': ('core.html#foo', 'ntest2/core.py')}}}